### ISSUE TITLE
TimeWarpException: Event overlap

### ISSUE THREAD

**Issue by agiertli** [mgm3746/garbagecat#116]
$ java -jar garbagecat-2.0.13-SNAPSHOT.jar -t 50 -p ~/Downloads/gc.log.0.current
Exception in thread "main" org.eclipselabs.garbagecat.domain.TimeWarpException: Event overlap:
2018-07-25T16:41:42.632-0400: 4070.967: [GC (Allocation Failure) [PSYoungGen: 3017378K->497170K(3282432K)] 11195125K->8783100K(11630080K), 0.4525147 secs] [Times: user=1.23 sys=0.68, real=0.46 secs]
2018-07-25T16:41:43.086-0400: 4071.414: [Full GC (Ergonomics) [PSYoungGen: 497170K->150789K(3282432K)] [ParOldGen: 8285930K->8347459K(8347648K)] 8783100K->8498248K(11630080K), [Metaspace: 2871321K->2850769K(3579904K)], 81.0232102 secs] [Times: user=35.53 sys=10.25, real=81.01 secs]
	at org.eclipselabs.garbagecat.util.jdk.JdkUtil.isBottleneck(JdkUtil.java:586)
	at org.eclipselabs.garbagecat.service.GcManager.getBottlenecks(GcManager.java:789)
	at org.eclipselabs.garbagecat.service.GcManager.getJvmRun(GcManager.java:876)
	at org.eclipselabs.garbagecat.Main.main(Main.java:160)

Same gc log file can be opened by GCViewer
https://github.com/chewiebug/GCViewer

gc log:
https://gist.github.com/agiertli/40ce17e15174c643e4a5804fc12c7a89

**Comment by mgm3746** [comment]
I guess GCViewer doesn't check if the timestamps make any sense or not. It works for them here, but IMO, that's very dangerous. IMO if the timestamps are out of order or do not make any sense (here the parallel scavenge is saying it ends after the following parallel old compacting event begins, something that isn't true), the tool should make you stop in your tracks and wonder why. For me, the error message is part of the analysis that you miss with GCViewer. IMO it's a rare scenario that requires manual thought and analysis.

For example, it's a very small time warp, so I can take 1 second off the first timestamp and make it 4069.967, which allows the file to be parsed and doesn't affect the analysis.

I can tell my looking at the next logging event that there is inverted parallelism. The JVM is very stressed out[1]. If you datafix the timestamp to remove the time warp, you will see:

"*There is evidence of inverted parallelism. With parallel (multi-threaded) collector events, the "user" time should be approximately equal to the "real" (wall) time multiplied by the # of GC threads. For example, if there are 3 GC threads we would expect a parallel collection that takes 1 second of "real" time to take approximately 3 seconds of "user" time. The parallelism is 3x. If the parallelism is 1x ("user" = "real"), the parallel collection is not offering any efficiency over a serial (single-threaded) collection. When "user" < "real", the parallelism is inverted. Inverted parallelism can be a sign of swapping or not enough CPU (e.g. GC threads competing with each other or other processes). Check for swapping and if the number of GC threads (-XX:ParallelGCThreads=<n>) is appropriate for the number of cpu/cores and any processes sharing cpu."

**Comment by mgm3746** [comment]
I would like to keep data fixing manual for now.
