### ISSUE TITLE
Unidentified log line: Entering safepoint region: RevokeBias

### ISSUE THREAD

**Issue by g122pl** [mgm3746/garbagecat#159]
Running garbagecat version: 3.0.6-SNAPSHOT
Latest garbagecat version/tag: v3.0.5

JDK version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

originally causing NPE during preprocessing:

```
Exception in thread "main" java.lang.NullPointerException
        at org.eclipselabs.garbagecat.preprocess.jdk.unified.UnifiedPreprocessAction.<init>(UnifiedPreprocessAction.java:718)
        at org.eclipselabs.garbagecat.service.GcManager.getPreprocessedLogEntry(GcManager.java:349)
        at org.eclipselabs.garbagecat.service.GcManager.preprocess(GcManager.java:192)
        at org.eclipselabs.garbagecat.Main.createReport(Main.java:131)
        at org.eclipselabs.garbagecat.Main.main(Main.java:90)
```

after adding nextLogEntry != null in line UnifiedPreprocessAction.java:718

```
----------------------------------------
info
----------------------------------------
*Last log line not identified. This is typically caused by the GC log being copied while the JVM is in the middle of logging an event, resulting in truncated logging. If it is not due to truncated logging, report the unidentified logging line: https://github.com/mgm3746/garbagecat/issues.
========================================
1 UNIDENTIFIED LOG LINE(S):
----------------------------------------
[2021-09-22T10:59:48.831-0500][5443308ms] Entering safepoint region: RevokeBias
========================================
```

**Comment by mgm3746** [comment]
This should be fixed now. Please test and let me know.

**Comment by g122pl** [comment]
Tested - NPE problem is fixed
