### ISSUE TITLE
docker: `--version` not working

### ISSUE THREAD

**Issue by mjtrangoni** [mgm3746/garbagecat#169]
Hi @mgm3746,

JFTR, there is still an issue with `--version` flag inside a container. 
See,
```bash
$ docker run -v "$PWD":/home/garbagecat/files:z ghcr.io/mgm3746/garbagecat:main --version
Exception in thread "main" java.util.MissingResourceException: Can't find bundle for base name META-INF/maven/garbagecat/garbagecat/pom, locale en
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
	at org.eclipselabs.garbagecat.OptionsParser.getVersion(OptionsParser.java:166)
	at org.eclipselabs.garbagecat.OptionsParser.parseOptions(OptionsParser.java:100)
	at org.eclipselabs.garbagecat.Main.main(Main.java:110)
```

**Comment by mgm3746** [comment]
hi @bostrt, any thoughts on how to fix this?

**Comment by mgm3746** [comment]
Local jar build with mvn package:
$ jar -tf target/garbagecat-4.0.1-SNAPSHOT.jar | grep garbagecat | grep -E "pom.properties"
META-INF/maven/garbagecat/garbagecat/pom.properties

pom.properties is missing from container jar:
jar -tf garbagecat.jar | grep garbagecat | grep -E "pom.properties"

**Comment by mgm3746** [comment]
I can reproduce the issue outside the container when building as follows:
$ mvn clean compile assembly:single

**Comment by mgm3746** [comment]
@mjtrangoni it seems to be resolved if I replace "mvn compile assembly:single" with "mvn package". Then the garbagecat pom.properties is included in the jar. Do you have any issue with changing it?
