### ISSUE TITLE
Exception in thread "main" org.eclipselabs.garbagecat.domain.TimeWarpException: Bad order:

### ISSUE THREAD

**Issue by Sarkie** [mgm3746/garbagecat#189]
Exception in thread "main" org.eclipselabs.garbagecat.domain.TimeWarpException: Bad order:
2023-03-18T16:39:00.010+0000: 812750.462: Total time for which application threads were stopped: 0.0010455 seconds, Stopping threads took: 0.0000263 seconds
2023-03-18T16:39:00.011+0000: 812750.463: Total time for which application threads were stopped: 0.0038515 seconds, Stopping threads took: 0.0001105 seconds
        at org.eclipselabs.garbagecat.util.jdk.JdkUtil.isBottleneck(JdkUtil.java:692)
        at org.eclipselabs.garbagecat.service.GcManager.getSafepointBottlenecks(GcManager.java:950)
        at org.eclipselabs.garbagecat.service.GcManager.getJvmRun(GcManager.java:1044)
        at org.eclipselabs.garbagecat.Main.createReport(Main.java:165)
        at org.eclipselabs.garbagecat.Main.main(Main.java:108)

I also tried using -r 

The log is 400mb, in case it's a size thing.

Thanks

**Comment by mgm3746** [comment]
Hi,

I'm sorry for the late reply. I did not catch this until now.

The reason for the exception is due to JDK8 logging precision.

The 2nd event supposedly has this begin time in nanoseconds after JVM start:
812,750,463,000,000 - (3,851,500 + 110,500) = 8,127,504,590,000

Which is not possible because the prior event supposedly ended at 812,750,462,000,000 nanoseconds after JVM start.

So the logging is saying the 2nd event started 1,000,000 nanoseconds (1 millisecond) before the first event.

The timings are just too small for the JDK to deal with.

I will change the code so it wont report this unless the time warp > 1 millisecond.

**Comment by Sarkie** [comment]
@mgm3746 Sorry, do you have a build bot link that i'm missing? Thanks

**Comment by mgm3746** [comment]
Hi @Sarkie, There is a github action that builds an image on each commit to the repo. 

So the latest code can always be run as a container by running the following in the directory where `gc-example.log` exists:

> $ docker run --pull=always -v "$PWD":/home/garbagecat/files:z ghcr.io/mgm3746/garbagecat:main --console /home/garbagecat/files/src/test/gc-example.log >> report.txt

The container has to have permission to access the local filesystem, so if you get a blank report, you may need to change the permissions on the gc log that is being analyzed per the following:
https://github.com/mgm3746/garbagecat/wiki/FAQs#what-causes-invalid-file-homegarbagecatfilesgclog-when-running-as-a-container

Let me know if you have any additional questions or issues.

**Comment by Sarkie** [comment]
Hi @mgm3746 
Honestly, I was just expecting a .jar file link to the latest snapshot as I can't install docker on my work laptop.
So in the end I installed maven and built it. So that's fine.

**Comment by Sarkie** [comment]
This fixed my issue, but you closed it already 👍
