### ISSUE TITLE
parsing G1 log throws exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mgm3746/garbagecat#33]
```
What steps will reproduce the problem?
1. parse attached G1GC log
2.
3.

What is the expected output? What do you see instead?

I expect parse to succeed, instead I see this:

Exception in thread "main" java.lang.NumberFormatException: For input string: 
"M"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:449)
        at java.lang.Integer.parseInt(Integer.java:499)
        at org.eclipselabs.garbagecat.domain.jdk.G1CleanupEvent.<init>(G1CleanupEvent.java:109)



What version of the product are you using? On what operating system?
I built from trunk.  Windows.

Please provide any additional information below.

The G1CleanupEvent needs to skip the 'K' and 'M" identifiers.  Was:
    public G1CleanupEvent(String logEntry) {
        this.logEntry = logEntry;
        Matcher matcher = pattern.matcher(logEntry);
        if (matcher.find()) {
            timestamp = JdkMath.convertSecsToMillis(matcher.group(12)).longValue();
            combined = Integer.parseInt(matcher.group(13)) * 1024;
            combinedEnd = Integer.parseInt(matcher.group(14)) * 1024;
            combinedAvailable = Integer.parseInt(matcher.group(15)) * 1024;
            duration = JdkMath.convertSecsToMillis(matcher.group(16)).intValue();
        }
    }

Change (The code also needs to take K versus M into consideration, my 'patch' 
does not do this:

    public G1CleanupEvent(String logEntry) {
        this.logEntry = logEntry;
        Matcher matcher = pattern.matcher(logEntry);
        if (matcher.find()) {
            timestamp = JdkMath.convertSecsToMillis(matcher.group(12)).longValue();
            combined = Integer.parseInt(matcher.group(13)) * 1024;
            combinedEnd = Integer.parseInt(matcher.group(15)) * 1024;
            combinedAvailable = Integer.parseInt(matcher.group(17)) * 1024;
            duration = JdkMath.convertSecsToMillis(matcher.group(19)).intValue();
        }
    }


```

Original issue reported on code.google.com by `skellic...@gmail.com` on 20 May 2013 at 11:44

Attachments:
* [gc_2013-05-20-14-53.log](https://storage.googleapis.com/google-code-attachments/garbagecat/issue-33/comment-0/gc_2013-05-20-14-53.log)

**Comment by mgm3746** [comment]
Unfortunately it looks like the attachments did not get migrated during the migration to github. With all the G1 work done during the last year, I'm betting this has been fixed. If not, please reopen and attach the logging.
