### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by bostrt** [mgm3746/garbagecat#63]
I'm getting this error when parsing attached gc log:

````
# garbagecat GConline1.1-gc.log 
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at java.math.BigDecimal.divideAndRound(BigDecimal.java:4106)
	at java.math.BigDecimal.divide(BigDecimal.java:5183)
	at java.math.BigDecimal.divide(BigDecimal.java:1561)
	at java.math.BigDecimal.divide(BigDecimal.java:1591)
	at org.eclipselabs.garbagecat.domain.JvmRun.getStoppedTimeThroughput(JvmRun.java:374)
	at org.eclipselabs.garbagecat.Main.createReport(Main.java:331)
	at org.eclipselabs.garbagecat.Main.main(Main.java:151)
````

[GConline1.1-gc.txt](https://github.com/mgm3746/garbagecat/files/717656/GConline1.1-gc.txt)

**Comment by bostrt** [comment]
https://github.com/mgm3746/garbagecat/blob/master/src/main/java/org/eclipselabs/garbagecat/domain/JvmRun.java#L374

**Comment by mgm3746** [comment]
https://github.com/mgm3746/garbagecat/commit/d075178a679bc0b334bf3ace036deb7411b7bdc9
