### ISSUE TITLE
Can't find resource for PropertyResourceBundle, key error.cms.new.serial.old

### ISSUE THREAD

**Issue by loleary** [mgm3746/garbagecat#65]
Processing fails with exception:

```
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key error.cms.new.serial.old
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at org.eclipselabs.garbagecat.util.GcUtil.getPropertyValue(GcUtil.java:184)
	at org.eclipselabs.garbagecat.Main.createReport(Main.java:399)
	at org.eclipselabs.garbagecat.Main.main(Main.java:151)
```
The following JVM command-line is what was used to generate this exception:

```
CommandLine flags: -XX:+DisableExplicitGC -XX:GCLogFileSize=209715200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/applog/coredir -XX:InitialHeapSize=3355443200 -XX:MaxHeapSize=3355443200 -XX:MaxPermSize=268435456 -XX:NewRatio=1 -XX:NumberOfGCLogFiles=5 -XX:PermSize=268435456 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:SurvivorRatio=3 -XX:-TraceClassUnloading -XX:+UseCompressedOops -XX:+UseGCLogFileRotation -XX:+UseParNewGC 
```

**Comment by loleary** [comment]
This issue was introduced by commit bfc249fcddca9a43b273ac5d55eabf6715b2dd49

Specifically, `cms.new.serial.old` was changed to `warn.cms.new.serial.old` in analysis.properties but `ERROR_CMS_NEW_SERIAL_OLD` was changed to `error.cms.new.serial.old` in Analysis.java.
